<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Requisition Slip #{{ $stockOut->stockout_id }}</title>
    <style>
        body {
            font-family: 'Courier New', Courier, monospace;
            font-size: 14px;
            color: #333;
            max-width: 800px;
            margin: 0 auto;
            padding: 20px;
        }

        .header {
            text-align: center;
            border-bottom: 2px dashed #333;
            padding-bottom: 10px;
            margin-bottom: 20px;
        }

        .header h1 {
            margin: 0;
            font-size: 20px;
            text-transform: uppercase;
        }

        .header p {
            margin: 5px 0 0;
            font-size: 12px;
        }

        .info-grid {
            display: grid;
            grid-template-columns: 1fr 1fr;
            gap: 20px;
            margin-bottom: 20px;
        }

        .info-row {
            margin-bottom: 8px;
        }

        .label {
            font-weight: bold;
            display: inline-block;
            width: 100px;
        }

        .items-table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
            border: 1px solid #333;
        }

        .items-table th,
        .items-table td {
            border: 1px solid #333;
            padding: 8px;
            text-align: left;
        }

        .footer {
            margin-top: 40px;
            border-top: 1px solid #333;
            padding-top: 10px;
            font-size: 12px;
            text-align: center;
        }

        .signatures {
            display: flex;
            justify-content: space-between;
            margin-top: 50px;
        }

        .sig-box {
            text-align: center;
            width: 200px;
            border-top: 1px solid #333;
            padding-top: 5px;
        }

        @media print {
            body {
                font-size: 12px;
            }

            .no-print {
                display: none;
            }
        }
    </style>
</head>

<body onload="window.print()">

    <div class="no-print" style="margin-bottom: 20px; text-align: right;">
        <button onclick="window.print()" style="padding: 8px 16px; cursor: pointer;">Print Slip</button>
        <button onclick="window.close()" style="padding: 8px 16px; cursor: pointer;">Close</button>
    </div>

    <div class="header">
        <h1>Material Requisition Slip</h1>
        <p>SubWFour Auto Services</p>
        <p>Date: {{ $stockOut->created_at->format('Y-m-d H:i') }}</p>
    </div>

    <div class="info-grid">
        <div>
            <div class="info-row"><span class="label">Slip ID:</span> {{ $stockOut->stockout_id }}</div>
            <div class="info-row"><span class="label">Date:</span>
                {{ \Carbon\Carbon::parse($stockOut->stockout_date)->format('M d, Y') }}</div>
        </div>
        <div>
            <div class="info-row"><span class="label">Requested By:</span> {{ $stockOut->user->name ?? 'N/A' }}</div>
            <div class="info-row"><span class="label">Reference:</span>
                @if($stockOut->reference_type)
                    {{ class_basename($stockOut->reference_type) }} #{{ $stockOut->reference_id }}
                @else
                    None
                @endif
            </div>
        </div>
    </div>

    <table class="items-table">
        <thead>
            <tr>
                <th>Item Code</th>
                <th>Description</th>
                <th style="text-align: right;">Quantity</th>
                <th>Unit</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>{{ $stockOut->item->item_id }}</td>
                <td>{{ $stockOut->item->name }}</td>
                <td style="text-align: right;">{{ $stockOut->quantity }}</td>
                <td>{{ $stockOut->item->unit ?? 'pcs' }}</td>
            </tr>
        </tbody>
    </table>

    <div style="margin-top: 20px;">
        <strong>Remarks/Notes:</strong>
        <p style="border-bottom: 1px solid #ccc; padding-bottom: 4px; min-height: 20px;">{{ $stockOut->remarks ?? '—' }}
        </p>
    </div>

    <div class="signatures">
        <div class="sig-box">
            Requested/Received By
        </div>
        <div class="sig-box">
            Approved By
        </div>
    </div>

    <div class="footer">
        Generated by SubWFour System on {{ now()->format('Y-m-d H:i:s') }}
    </div>

</body>

</html>